// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBJIdC_43Eptgg9L_rER2vjTuRJSYL-MZA',
    appId: '1:451592121635:web:72028523e6cb0414163096',
    messagingSenderId: '451592121635',
    projectId: 'tinkerpro-sports',
    authDomain: 'tinkerpro-sports.firebaseapp.com',
    storageBucket: 'tinkerpro-sports.firebasestorage.app',
    measurementId: 'G-RPV0YNL9C5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC9Cdko8OUkzZBwpUnRDccOMln6Loh7iW4',
    appId: '1:451592121635:android:c04429b571587cc6163096',
    messagingSenderId: '451592121635',
    projectId: 'tinkerpro-sports',
    storageBucket: 'tinkerpro-sports.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB37H9UVNAIs3T6gUXsuWV-9otNf-IEAX8',
    appId: '1:451592121635:ios:69af062a64e4ae04163096',
    messagingSenderId: '451592121635',
    projectId: 'tinkerpro-sports',
    storageBucket: 'tinkerpro-sports.firebasestorage.app',
    iosBundleId: 'com.example.myapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB37H9UVNAIs3T6gUXsuWV-9otNf-IEAX8',
    appId: '1:451592121635:ios:69af062a64e4ae04163096',
    messagingSenderId: '451592121635',
    projectId: 'tinkerpro-sports',
    storageBucket: 'tinkerpro-sports.firebasestorage.app',
    iosBundleId: 'com.example.myapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBJIdC_43Eptgg9L_rER2vjTuRJSYL-MZA',
    appId: '1:451592121635:web:a36e6eed626dac47163096',
    messagingSenderId: '451592121635',
    projectId: 'tinkerpro-sports',
    authDomain: 'tinkerpro-sports.firebaseapp.com',
    storageBucket: 'tinkerpro-sports.firebasestorage.app',
    measurementId: 'G-N4VF5M46X6',
  );
}
